# Use postgres/example user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: bbusters
      MONGO_INITDB_ROOT_PASSWORD: securepassword
    ports:
      - '27017-27019:27017-27019'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: bbusters
      ME_CONFIG_MONGODB_ADMINPASSWORD: securepassword
  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - 8080:8080
